name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        PG_DATA_VOLUME: ${{ secrets.PG_DATA_VOLUME }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_USERNAME: ${{ secrets.PG_USERNAME }}
        PG_DBNAME: ${{ secrets.PG_DBNAME }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs:
          - PG_DATA_VOLUME,PG_PASSWORD,PG_USERNAME,PG_DBNAME
        script: |
          cd ~/projects/patreon-statistics
          git pull
          docker-compose up
